INSERT INTO iloiloblog.galleries (title,body,tag,image_path,created_at,updated_at) VALUES
	 ('Binanog Festival','The Binanog Festival is a yearly festivity in Lambunao, Iloilo. This event is done in honor of the infant Jesus. It is a celebration that features several activities, dance rituals, performances, and competitions that add fun and color to the festival attracting crowds of locals and tourists for a week-long merriment.
    The Binanog dance is inspired by the “banog,” a Filipino term for hawk. The dance imitates the movement of a hawk, which makes it an interesting performance to witness. The dance consists of three forms. One is the “Binanugan,” which is the imitation part, the “Inagong sayaw-sayaw,” which is the celebratory dance, and the last part is the “Dinagmay,” a courtship dance.','festival','festival/binanogfest.jpg',NULL,NULL),
	 ('Leganes Saad Festival','Saad or ''Vow,'' is one of the major festivals in Iloilo. It is a mixture of Catholic and ancient local influences. Various religious ceremonies, enthusiasm paralleled with ample fun and celebration marks the festivity adding colour and integrity to the municipality.','festival','festival/leganessaadfest.jpg',NULL,NULL),
	 ('Dinagyang Festival','Dinagyang Festival is one of the biggest and world-class festivals in the Philippines. It traces the history of devotion to the Holy Child Jesus popularly known to Filipino devotees as Sr. Sto. Nino. The festival also commemorates the arrival of the Malays and the barter of Panay Island from the indigenous group known as Ati.','festival','festival/dinagyang2.png',NULL,NULL),
	 ('Jimanban Festival','Jimanban was the original name of New Lucena, a small community organized sometime in 1800 that was then an arrabal of the municipality of Cabatuan. Jimanban was derived from the word “nagapanghimanban” or to clear the place of banban grass in preparation for planting palay.','festival','festival/Jimanban.jpg',NULL,NULL),
	 ('Hirinugyaw-Suguidanonay Festival','Hirinugyaw-Suguidanonay Festival is an annual cultural, religious, and food festival in the municipality of Calinog in the province of Iloilo, Philippines. It starts January 24 and ends February 2. Its celebration is one offered to Sto. Niño and it is also a showcase of culture and identity of the indigenous people of Panay Bukidnon.','festival','festival/Hirinugyawfest.jpg',NULL,NULL),
	 ('Kasadyahan Festival','Kasadyahan is part of the Dinagyang Festival held annually in Iloilo, Philippines. This particular event celebrates the cultural aspects of the region. Held on the Saturday prior to the more familiar Ati-Tribes street dancing competition on the Sunday.','festival','festival/Kasadyahan.jpg',NULL,NULL),
	 ('Candelaria Fiesta','This is a festival full of culture, dance and music which brings together the catholic faith and Andean religion in homage to the Virgin of Candelaria. The Virgin represents fertility and purity, is the patron saint of the city and is strongly associated with ''pachamama'' (''mother earth'').','festival','festival/Candelaria.jpg',NULL,NULL),
	 ('Paraw Regatta Festival','It was inspired by history which dates back in 1212 A.D. Etymologically, ''Paraw'' in the local dialect means a sailboat, which is a native outrigger based in the design and materials of the sailboats that carried to Panay Island the first Bornean settlers who were in search of a peaceful home.','festival','festival/Paraw.jpg',NULL,NULL),
	 ('Hablon','Hablon is a handwoven textile from Iloilo traditionally made with a handloom using natural fibers such as abaca, piña, and cotton. The term hablon comes from the Hiligaynon word “habol”, which means “to weave”, and it can be used to describe both the process of weaving and the fabric itself.','products','products/Hablon.jpg',NULL,NULL),
	 ('Rice','The agri-industrial area of Iloilo is found in the central part of the province. Aside from sugar, agricultural products such as corn, rice, bananas, and pineapples can be found here. Iloilo has one of the highest number of farms among the Western Visayas provinces.','products','products/Rice.jpg',NULL,NULL);
INSERT INTO iloiloblog.galleries (title,body,tag,image_path,created_at,updated_at) VALUES
	 ('Corn','The agri-industrial area of Iloilo is found in the central part of the province. Aside from sugar, agricultural products such as corn, rice, bananas, and pineapples can be found here. Iloilo has one of the highest number of farms among the Western Visayas provinces.','products','products/Corn.jpg',NULL,NULL),
	 ('Poultry','The agri-industrial area of Iloilo is found in the central part of the province. Aside from sugar, agricultural products such as corn, rice, bananas, and pineapples can be found here. Iloilo has one of the highest number of farms among the Western Visayas provinces.','products','products/Poultry.jpg',NULL,NULL),
	 ('Mango','Guimaras mangoes'' reputation as ''sweetest'' now protected. Guimaras ILOILO CITY – Guimaras now solely owns the title of producing the sweetest mangoes following the conferment of the certificate of geographical indication (GI) registration by the Intellectual Property Office of the Philippines (IPOPHL).','products','products/Mango.jpg',NULL,NULL),
	 ('Watermelon','Western Visayas is now the top producer of watermelon in the Philippines.','products','products/watermelon.jpg',NULL,NULL),
	 ('Pineapple','When it comes to pineapples, the name of Passi will top the list. Passi City is a huge pineapple producer for years. Fruit processing of pineapples is also Passi’s industry. Aside from Passi, the towns of Miag-ao and Oton are also main producers of pineapples.','products','products/pineapple.jpg',NULL,NULL),
	 ('La Paz Batchoy','Batchoy, alternatively spelled batsoy, is a Filipino noodle soup of pork offal, crushed pork cracklings, chicken stock, beef loin, and round noodles. The original and most popular variant, the La Paz batchoy, traces its roots to the Iloilo City district of La Paz, in the Philippines.','delicacies','delicacies/batchoy.jpg',NULL,NULL),
	 ('Pancit Molo','Pancit Molo or Filipino pork dumpling soup is a type of soup using wonton wrappers which originated from Molo district in Iloilo City, Philippines. It consists of a mixture of ground pork wrapped in molo or wonton wrapper, shredded chicken meat, and also shrimp.','delicacies','delicacies/pancitmolo.jpg',NULL,NULL),
	 ('Biscocho','Biscocho, also spelled biskotso, refers to various types of Filipino twice-baked breads, usually coated with butter and sugar, or garlic in some cases. Biscocho is most strongly associated with the versions from the province of Iloilo, although it actually exists nationwide in various forms.','delicacies','delicacies/Biscocho.jpg',NULL,NULL),
	 ('Baye-Baye','Baye-Baye is a Filipino dish made from grated young coconut mixed with either newly harvested rice or corn and shaped into patties. It is a specialty of Pavia, Iloilo.','delicacies','delicacies/Baye.jpg',NULL,NULL),
	 ('Cansí','Cansí is a Filipino beef soup originating from Iloilo which is spread across the rest of the Western Visayas region. It is made with beef shank and bone marrow boiled until gelatinous. It is uniquely slightly soured with fruits like batuan or bilimbi.','delicacies','delicacies/Cansí.jpg',NULL,NULL);
INSERT INTO iloiloblog.galleries (title,body,tag,image_path,created_at,updated_at) VALUES
	 ('Ibos','We call it ibos but some parts of the country call it suman. It is made from glutinous rice (pilit) cooked using coconut milk (gata). Preparation would vary but most would soak the pilit in gata and carefully wrapped them one by one using coconut leaves (lukay). Then they will be placed inside a big kaldero and the rest of gata will serve as the water to soften the pilit.','delicacies','delicacies/ibos.jpg',NULL,NULL),
	 ('Inday-Inday','Inday-Inday is like suman latik but instead of getting wrapped in banana leaf, it is flattened above it. And the pilit used is the one grinded, formed into circles and placed on top of banana leaf. Then the finale is being topped with bukayo that will serve as the sweetener.','delicacies','delicacies/inday2.jpg',NULL,NULL),
	 ('Bukayo','Bukayo is candied coconut. It is a favorite “sweetener” for our Inday Inday and Suman Latik. This is also best palaman (spread) to our pandeleche or pandesal. The main ingredients are buko (coconut) strings and muscovado sugar. Some would prefer to form it into balls or flattened circle and left it to harden for a chewy product.','delicacies','delicacies/Bukayo.jpg',NULL,NULL),
	 ('Pinasugbo','Pinasugbo is a food made from thinly sliced banana (sab-a) and deeply fried in oil then dipped into caramelized sugar topped with sesame seeds. It is locally served with white paper cones which serves as the handle so can eat it without getting your fingers messy.','delicacies','delicacies/Pinasugbo.jpg',NULL,NULL);
